### ISSUE TITLE
updated for swift 5

### ISSUE THREAD

**Issue by birdsoftware** [boominadhaprakash/AnalogClock#1]
To make this run correctly in swift 5  I just needed to make 2 changes. I got the hour, minute and second components using Calendar and removed shown commented out below. Next I commented out the +180 for LayerAnimation

  //[1]
          // *** Get Individual components from date ***
            static let hour = Calendar.current.component(.hour, from: Date())
            static let minute = Calendar.current.component(.minute, from: Date())
            static let second = Calendar.current.component(.second, from: Date())
            
//            let hour1 = CGFloat(hour * (30))//360/12 =30
//            let hour2 = CGFloat(minutes)//1/60*360/12 = 1/60*30=0.5
//            static let hour = hour1 + hour2
//            //static let hour = (CGFloat(Date().hour * (360/12)) + (CGFloat(Date().minute) * (1.0/60) * (360/12)))
//            static let minute = CGFloat(minutes * (360/60))
//            static let second = CGFloat(seconds * (360/60))

//[2]
extension AnalogClockView {
    func secondLayerAnimation() {
        let secondAnimation = setUpLayerAnimation(duration: 60, isRemovedOnCompletion: false, timingFunction: CAMediaTimingFunction(name: .linear), fromValue: CGFloat(Angle.second/*+180*/) * CGFloat(Double.pi / 180), byValue: (2 * Double.pi))
        secondLayer.add(secondAnimation, forKey: AnimationKey.second)
    }
    func minuteLayerAnimation() {
        let minuteAnimation = setUpLayerAnimation(duration: 60*60, isRemovedOnCompletion: false, timingFunction: CAMediaTimingFunction(name: .linear), fromValue: (Double(Angle.minute/*+180*/) * Double.pi / 180), byValue: 2 * Double.pi)
        minuteLayer.add(minuteAnimation, forKey: AnimationKey.minute)
    }
    func hourLayerAnimation() {
        let hourAnimation = setUpLayerAnimation(duration: 60*60*12, isRemovedOnCompletion: false, timingFunction: CAMediaTimingFunction(name: .linear), fromValue: (Double(Angle.hour/*+180*/)  * Double.pi / 180), byValue: 2 * Double.pi)
        hourLayer.add(hourAnimation, forKey: AnimationKey.hour)
    }
}

**Comment by boominadhaprakash** [comment]
Hi @birdsoftware 

Thank you. I will update my repo to Swift 5.

**Comment by boominadhaprakash** [comment]
Hi @birdsoftware 

But for me, it is already working correctly in Swift 5 without any changes. If possible can you modify the code and give me the pull request. I will merge with master.
